name: GitHub Pages Action

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2.1.0
              with:
                  node-version: '12.x'

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - run: npm ci
            - run: npm test

            - name: Generate
              run: npm run generate
              env:
                  NUXT_ENV_MAILGUN_PRIVATE_API_KEY: ${{ secrets.NUXT_ENV_MAILGUN_PRIVATE_API_KEY }}
                  NUXT_ENV_MAILGUN_DESTINATION_EMAIL_ADDRESS: ${{ secrets.NUXT_ENV_MAILGUN_DESTINATION_EMAIL_ADDRESS }}

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist
